### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Aries-Wu** [LTLA/tsvd#1]
Hi, I'm interested in the code you provided, could you provide a simple example to help me understand?
Thank you very much!

**Comment by LTLA** [comment]
Hm. I never continued with this because I ended up using https://github.com/LTLA/CppIrlba instead. You may find that easier to read, unless you specifically want to use randomized SVD.

**Comment by Aries-Wu** [comment]
Thanks for the new link, I found it much easier to understand!
